- src/pages/proposal-details/voting.tsx
- src/pages/proposals/proposal-dialog/voting.tsx
- src/pages/stake/delegate-dialog/index.tsx
- src/pages/stake/delegate-dialog/pending-dialog.tsx
- src/pages/stake/delegate-dialog/success-dialog.tsx
- src/pages/stake/delegate-dialog/un-success-dialog.tsx
- Fix style of tx modals
- Fix tx modals to show on any non-zero code
> DEV-429 Fix tx modals

- .env.testnet
- .env.testnet.local
- src/components/nft-id/id-form.tsx
- src/components/nft-id/id-preview.tsx
- src/components/nft-id/private-view.tsx
- src/config-insync.ts
- src/pages/stake/delegate-dialog/confirm-dialog.tsx
- src/pages/stake/delegate-dialog/success-dialog.tsx
- src/pages/stake/delegate-dialog/un-success-dialog.tsx
- src/stores/wallet/index.ts
- src/stores/wallet/messages/nftid.ts
- Fix missing minting_fee nftid param for metamask
- Add confirmation prompt to mint nft id
- Add metamask specific explorer url for testnet
> DEV-380 NFT ID Confirmation and ExplorerUrl for Metamask

- proto/rebus/nftid/v1/id.proto
- src/proto/rebus/nftid/v1/id.ts
- src/proto/rebus/nftid/v1/id_pb.d.ts
- src/proto/rebus/nftid/v1/id_pb.js
- src/stores/wallet/messages/nftid.ts
> DEV-380 Fix nftid type enum

- src/components/nft-id/private-view.tsx
- src/stores/wallet/messages/nftid.ts
> DEV-380 Fix nft id keplr params

- patches/@cosmjs+stargate+0.29.4.patch
- src/utils/helper.ts
Fix the helper file to work with the new cosmjs and update patch file.
> update patch and helper files for new cosmjs

- package.json
- src/components/nft-id/id-card.tsx
- src/components/nft-id/id-form.tsx
- src/components/nft-id/id-preview.tsx
- src/components/nft-id/private-view.tsx
- src/constants/questions.ts
- src/pages/nft-id/index.tsx
- src/pages/nft-id/questions/quiz-complete.tsx
- src/pages/nft-id/questions/quiz.tsx
- webpack.config.js
- yarn.lock
- Fix crossorigin style fetching issue when rendering nftid image
- Fix nftid not rendering properly on first load sometimes
- Refactored NFT ID flow to Create Id Record before the NFT ID page
- Fixed a few styles
> DEV-435 NFT ID Updates

- patches/@cosmjs+stargate+0.27.1.patch
- src/utils/helper.ts
Fix keplr signing for amino nftid txs
> DEV-435 Fix keplr signing for amino nftid txs

- src/stores/wallet/messages/mint-nft-id.ts
Fix mint nft id type for metamask
> DEV-435 Fix mint nft id type for metamask

- src/components/nft-id/id-preview.tsx
- src/components/nft-id/private-view.tsx
- Update nftid private view with ability to show/hide private id
- Fix Current ID section mobile view button layout
> DEV-435 Update nftid private view with ability to show/hide private id

- src/pages/nft-id/questions/getting-started.tsx
- src/pages/nft-id/questions/quiz.tsx
- src/stores/wallet/index.ts
- src/utils/helper.ts
Show error messaging if attempting to create nftid while not having an account
> DEV-453 Show better error message for account not found

- src/components/nft-id/id-preview.tsx
Fix flag not loading sometimes in nftid
> DEV-460 Fix flag not loading sometimes in nftid

- src/components/nft-id/active-dot.tsx
- src/components/nft-id/id-preview.tsx
- src/pages/nft-id-view/index.tsx
Add dot showing active status on public nftid view
https://user-images.githubusercontent.com/121109658/217651707-683080c1-42ef-4051-bb98-fe01816ccc38.mp4
> DEV-481 Add dot showing active status on public nftid view

- .github/workflows/action-build-lint.yml
Update node version used in github build action.
> update node version for build aciton

- .babelrc
- .github/workflows/deploy-ui-branch.yml
- package.json
- src/components/nft-id/id-preview.tsx
- src/pages/nft-id/questions/getting-started.tsx
- src/utils/helper.ts
- yarn.lock
fix breaking build on epic branch
> Fix epic branch pt2

- .env.mainnet
- .env.mainnet.local
- Add missing explorer url for mainnet
> Add missing explorer url for mainnet

- src/reducers/slices/proposals/slices/items.ts
- src/reducers/slices/proposals/slices/proposal-details.ts
- src/reducers/slices/proposals/slices/tally-details.ts
- src/reducers/slices/proposals/slices/vote-details.ts
- src/reducers/slices/proposals/slices/votes.ts
- src/reducers/slices/stake/slices/delegated-validators.ts
- src/reducers/slices/stake/slices/validator-details.ts
- src/reducers/slices/stake/slices/validators.ts
This PR fixes the unsafe header messages in the console.
> feat(Dev-436): remove connection keep alive

- src/pages/ibc-transfer/address-input.tsx
fix the button animation for the keplr button
https://user-images.githubusercontent.com/117384613/228595850-2864f27f-c76e-4ca8-8adf-6f3c0eaf8ce3.mov
> fix button animation

- src/pages/wallet-connect/index.tsx
Fix cosmos verify bot connecting with metamask
> Fix cosmos verify bot connecting with metamask

- patches/@keplr-wallet+stores+0.9.12-rc.3.patch
- src/pages/proposal-details/index.tsx
- src/pages/proposals/new-cards.tsx
- src/pages/proposals/tooltip-graph-section.tsx
- src/utils/color-formatter.ts
- src/utils/proposal-status.ts
- src/utils/vote-calculation.ts
Fix deprecated calls for proposals and get UI Working with new data structure
> Dev 571 fix vote UI

- src/pages/proposals/new-cards.tsx
> fix voting percentages

- src/pages/proposals/new-cards.tsx
> fix no tooltip

- src/pages/tools/components/address-converter/index.tsx
> feat(Dev-631): add conversion tool modal

- src/pages/assets/asset-balances-list.tsx
- src/stores/wallet/index.ts
> Remove leftover log

- patches/@cosmjs+stargate+0.29.4.patch
> DEV-694 Fix keplr EVM signing

- package.json
- src/colors.tsx
- src/components/common/slider.tsx
- src/components/insync/text-field/text-field.tsx
- src/index.tsx
- src/pages/assets/index.tsx
- src/theme.tsx
- yarn.lock
The old TextField and Slider PR got removed, but here is a identical new one with a verified signature. Should be good to go :)
Dark Mode:
Light Mode:
> DEV-684 Textfield and Slider redesign with light/dark mode

- src/components/common/tab-bar.tsx
- src/pages/assets/index.tsx
> DEV-687 Tab component redesign with light/dark mode

- patches/@cosmjs+stargate+0.29.4.patch
- src/components/common/checkbox.tsx
- src/components/common/modal.tsx
- src/pages/assets/index.tsx
I created a blurred background to present the modal, but that can be easily be removed
Dark Mode:
Light Mode:
> DEV-685 Modal component redesign with light dark mode

- src/constants/wallet.ts
Update wallet network versions
> DEV-699 Update wallet network versions

- patches/@cosmjs+stargate+0.29.4.patch
Fix cosmjs stargate patch to fix keplr evmos signing
> DEV-713 Fix cosmjs stargate patch to fix keplr evmos signing

- .env.testnet
- .env.testnet.local
update test net endpoints. @pierstab let me know If I should update anything else
> update testnet endpoints

- src/stores/wallet/index.ts
Update testnet chain id for evm
> DEV-804 Update testnet chain id for evm

- src/dialogs/convert.tsx
- src/utils/helper.ts
Use amino sign when signing on regular keplr wallet for convert transactions
> DEV-806 Convert with Amino Sign

- src/config.ts
> Fix COM minimal denom

- .env.alphanet
- .env.mainnet
- .env.mainnet.local
- public/keplr-mainnet.html
- public/wallet.html
- public/wax-rebus-airdrop.html
Update chain id from 1111 to 1011
> DEV-846 Update chain id from 1111 to 1011

- .env
- .env.mainnet
- .env.mainnet.local
- src/stores/wallet/index.ts
> DEV-846 Update chain info for evm
